# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  database: irtd_dev

production:
  adapter: postgresql
  host: localhosr
  username: postgres
  password: postgres
  database: irtd_dev
