# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: sqlite3
  database: db/development.sqlite3

production:
  adapter: postgresql
  host: 201.49.38.20
  username: dute
  password: dute*&098
  database: irtd_dev
